#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from ecn_2024.srv import Letter
from geometry_msgs.msg import Point
from matplotlib.text import TextPath
import numpy as np


class Builder(Node):
    def __init__(self):
        super().__init__('letter2path')
        self.srv = self.create_service(Letter, '/plan', self.plan_cb)

    def plan_cb(self, req: Letter.Request, res: Letter.Response):

        res.contour = []

        if len(req.letter) >= 1:

            path = [v for v in TextPath((0,0), req.letter[0], size=12).vertices if np.linalg.norm(v) > 1e-3]
            path.append(path[0])
            steps = [path[0]]

            for wp in path[1:]:
                last = steps[-1]
                for a in np.linspace(0, 1, int(np.linalg.norm(last-wp)/0.3) + 1):
                    steps.append(a*wp + (1-a)*last)

            for x,y in steps:
                p = Point()
                p.x = req.x+x
                p.y = req.y+y
                res.contour.append(p)
        return res


rclpy.init()
node = Builder()

rclpy.spin(node)

# clean exit on Ctrl-C
node.destroy_node()
rclpy.shutdown()

